---
build_from:
  aarch64: ghcr.io/home-assistant/aarch64-base:3.21
  amd64: ghcr.io/home-assistant/amd64-base:3.21
args:
  OTBR_BETA_VERSION: 78d9c289473602d3faab535c4e7fbd12ca8d32f5
  OTBR_VERSION: 624a7d98e0dac5984c2982068f71fc81d2dbceb5
  AIOSPINEL_VERSION: 1.0.0
  SERIALX_VERSION: 1.8.0
